### ISSUE TITLE
Gradle Sync Issues 

### ISSUE THREAD

**Issue by jamattey** [GADS-Group-E/BeeSmart-Android-App#2]
Hello @Confidence-bassey, kindly check the version of your Android Gradle plugin. 

Please review 
<img width="1369" alt="Screenshot 2022-11-17 at 5 39 28 PM" src="https://user-images.githubusercontent.com/69109175/202518209-408c903c-d2d4-4b1c-83a4-ce1e968d6aa9.png">

**Comment by Confidence-bassey** [comment]
Hello @jamattey, I have reviewed it. I have the current version of android studio running on my system and the build is successful. I think you should update your android studio to the latest version so it can run on your system, because I once had the bug but it disappeared immediately I updated my android studio version. Thanks.

**Comment by jamattey** [comment]
Resolved, thank you
